### ISSUE TITLE
docs for fmr, and still no parsy

### ISSUE THREAD

**Issue by gabrielgellner** [bis-med-it/pysdmx#149] opened 2024-12-09 20:55 UTC
In #97 parsy was meant to be added as a non optional install, but on a fresh install today (pysdmx[fmr]>=1.0.0rc5") I still get an error for parsy not being installed.

Also documentation does not reflect the change from pysdmx.fmr -> pysdmx.api.fmr

**Comment by sosna** [comment] 2024-12-10 14:43
Thanks, @gabrielgellner. Work on updating the documentation will start soon, as most of the features required for a 1.0.0 release have been implemented.

Re. parsy, it is an optional dependency, as you can see in the [pyproject.toml file](https://github.com/bis-med-it/pysdmx/blob/5f559fae62c72528f566e0728d7b9bc7ea4a54cf/pyproject.toml#L30). And, as can be seen 4 lines below, you need to install the package with the `dc` option.

For example, if you use `poetry` to add `pysdmx` as a dependency to your project, you would need to do something like: 
`poetry add pysdmx[dc]@^1.0.0.rc5`

Most of the dependencies are optional, so you need to know what you intend to use from the library and add the necessary options (the list will be part of the updated documentation).

**Comment by gabrielgellner** [comment] 2024-12-10 15:28
Just to clarify, we were trying out the fmr stuff, so did `add pysdmx[fmr]` but when you do from `pysdmx.api.fmr import <stuff you want>` you get the missing parsy error. I can try to [dc] optional install instead, but just wanted to clarify if the fmr option is deprecated, or needs to declare the parsy stuff?

**Comment by sosna** [comment] 2024-12-12 09:55
Thanks, @gabrielgellner. Indeed, the issue is still there, as now parsy is also used in one of the model classes, i.e. one of the core modules of the library. I have fixed the issue in #150

**Closed** 2024-12-12 11:02 UTC
